# Generated by Django 3.2.9 on 2022-01-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='sending',
            field=models.TextField(default='', max_length=100),
        ),
    ]
