# Generated by Django 3.2.9 on 2022-02-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0003_remove_emails_sending'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emails',
            new_name='emailsdatabase',
        ),
    ]
