# Generated by Django 3.2.9 on 2022-02-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0004_rename_emails_emailsdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='emy',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='emailsdatabase',
        ),
    ]
