# Generated by Django 3.2.9 on 2022-02-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0005_auto_20220203_1035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emy',
            new_name='Emailsdatabase',
        ),
    ]
